apiVersion: v2
name: ingress-nginx
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: '1.16.0'

dependencies:
  - name: ingress-nginx
    version: v4.2.0
    repository: https://kubernetes.github.io/ingress-nginx
