replicaCount: 1

image:
  repository:
  pullPolicy: Always
  tag: production

imagePullSecrets:
  - name: tarrasque
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  # Key to store randomized chart id to force redeployment
  randomChartId: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
  hosts:
    - host: tarrasque.app
      paths:
        - path: /()(.*)
          pathType: Prefix
    - host: www.tarrasque.app
      paths:
        - path: /()(.*)
          pathType: Prefix
  tls:
    - secretName: tls-secret-ui
      hosts:
        - tarrasque.app
        - www.tarrasque.app

env:
  - name: VERSION
    value: "1.0.0"
  - name: HOST
    value: "https://tarrasque.app"
  - name: AXIOS_BASE_URL
    value: "https://tarrasque.app"
  - name: NODE_ENV
    value: "production"
  - name: JWT_ACCESS_TOKEN_EXPIRATION_TIME
    value: "5m"
  - name: SENTRY_ENABLED
    value: "true"
  - name: SENTRY_DSN
    value: ""

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
